### ISSUE TITLE
ShuffleArray is not define for random playback in node_helper.js

### ISSUE THREAD

**Issue by aigmixer** [pelaxa/MMM-ImmichSlideShow#8]
error:

```
0|mm  | [22.01.2024 21:44.25.393] [INFO]  MMM-ImmichSlideShow :: node_helper :: imageList is Array? true
0|mm  | [22.01.2024 21:44.25.396] [ERROR] (node:57312) UnhandledPromiseRejectionWarning: ReferenceError: shuffleArray is not defined
0|mm  |     at Class.sortImageList (/home/gmixer/MagicMirror/modules/MMM-ImmichSlideShow/node_helper.js:98:9)
0|mm  |     at Class.gatherImageList (/home/gmixer/MagicMirror/modules/MMM-ImmichSlideShow/node_helper.js:273:27)
0|mm  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|mm  | (Use `electron --trace-warnings ...` to show where the warning was created)
0|mm  | [22.01.2024 21:44.25.397] [ERROR] (node:57312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

```
case 'random':
        // Log.log(LOG_PREFIX + 'Sorting by modified date...');
        sortedList = shuffleArray(imageList); // Use 'this' to refer to the method
        break;
```

needs to be:

```
case 'random':
        // Log.log(LOG_PREFIX + 'Sorting by modified date...');
        sortedList = this.shuffleArray(imageList); // Use 'this' to refer to the method
        break;
```

**Comment by pelaxa** [comment]
Thanks for reporting this.  Never used that option, but fix coming soon

**Comment by aigmixer** [comment]
Thanks!
